apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.annotations.config }}
  annotations: {{- toYaml .Values.annotations.config | nindent 8 }}
{{- end }}
{{- if .Values.extraLabels.config }}
  labels: {{- toYaml .Values.extraLabels.config | nindent 8 }}
{{- end }}
data:
  tbot.yaml: |
    {{- if .Values.customConfig }}
    {{- toYaml .Values.customConfig | nindent 4 }}
    {{- else }}
    version: v2
    {{- if .Values.teleportProxyAddress }}
    proxy_server: {{ .Values.teleportProxyAddress }}
    {{- end }}
    {{- if .Values.teleportAuthAddress }}
    auth_server: {{ .Values.teleportAuthAddress }}
    {{- end }}
    onboarding:
      join_method: {{ .Values.joinMethod }}
      token: {{ .Values.token }}
    storage:
      type: kubernetes-secret
      name: {{ .Release.Name }}-data
    {{- if .Values.defaultOutput.enabled }}
    outputs:
      - type: identity
        destination:
          type: kubernetes-secret
          name: {{ .Values.defaultOutput.secretName }}
    {{- end }}
    {{- end }}
