apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.annotations.config }}
  annotations: {{- toYaml .Values.annotations.config | nindent 8 }}
{{- end }}
{{- if .Values.extraLabels.config }}
  labels: {{- toYaml .Values.extraLabels.config | nindent 8 }}
{{- end }}
data:
  tbot.yaml: |
    version: v2
    # outputs will be filled in during the completion of an access guide.
    outputs: []