apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
{{- if .Values.extraLabels.deployment }}
  {{- toYaml .Values.extraLabels.deployment | nindent 4 }}
{{- end }}
  {{- if .Values.annotations.deployment }}
  annotations: {{- toYaml .Values.annotations.deployment | nindent 4 }}
  {{- end }}
spec:
  # Replicas are set to 1 until we establish a locking mechanism for the
  # `kubernetes_secret` destination.
  replicas: 1
  strategy:
    # Recreate strategy until we establish a locking mechanism for the
    # `kubernetes_secret` destination.
    type: Recreate
  selector:
    matchLabels: {{- include "tbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.annotations.pod }}
      annotations: {{- toYaml .Values.annotations.pod | nindent 8 }}
    {{- end }}
      labels:  {{- include "tbot.labels" . | nindent 8 }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
    {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector: {{- toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations: {{- toYaml .Values.tolerations | nindent 8 }}
    {{- end }}
      containers:
        - name: tbot
          image: {{ .Values.image }}:{{ .Chart.Version }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args:
            - start
            - -c
            - /config/tbot.yaml
            - --debug # Make this configurable.
            - --log-format
            - json
          env:
            # POD_NAMESPACE is required for the kubernetes_secret` destination
            # type to work correctly.
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # TELEPORT_NODE_NAME is required for Workload Identity Kubernetes
            # Workload Attestation to work correctly.
            - name: TELEPORT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # KUBERNETES_TOKEN_PATH specifies the path to the service account
            # JWT to use for joining.
            # This path is based on the configuration of the volume and
            # volumeMount.
            - name: KUBERNETES_TOKEN_PATH
              value: /var/run/secrets/tokens/join-sa-token
          {{- if .Values.anonymousTelemetry }}
            - name: TELEPORT_ANONYMOUS_TELEMETRY
              value: "1"
          {{- end }}
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /var/run/secrets/tokens
              name: join-sa-token
        {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
      serviceAccountName: {{ template "tbot.serviceAccountName" . }}
      volumes:
        - name: config
          configMap:
            name: tbot-config
        - name: join-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: join-sa-token
                  # 600 seconds is the minimum that Kubernetes supports. We
                  # recommend this value is used.
                  expirationSeconds: 600
                  audience: {{ .Values.clusterName }}