{{ if not .Values.customConfig }}
  {{ if not (or .Values.teleportAuthAddress .Values.teleportProxyAddress) }}
    {{- required "When `customConfig` has not been set, `teleportAuthAddress` or `teleportProxyAddress` must be provided" "" }}
  {{ end }}
  {{ if not .Values.clusterName }}
    {{- required "When `customConfig` has not been set, `clusterName` must be provided" "" }}
  {{ end }}
  {{ if not .Values.token }}
    {{- required "When `customConfig` has not been set, `token` must be provided" "" }}
  {{ end }}
  {{ if and (.Values.defaultOutput.enabled) (not .Values.defaultOutput.secretName) }}
    {{- required "When `customConfig` has not been set, `defaultOutput.secretName` must be provided" "" }}
  {{ end }}
{{ end }}
{{ if (and .Values.teleportAuthAddress .Values.teleportProxyAddress) }}
  {{- required "`teleportAuthAddress` and `teleportProxyAddress` are mutually exclusive" "" }}
{{ end }}