# This role grants the ability to manage secrets within the namespace - this is
# necessary for the `kubernetes_secret` destination to work correctly.
#
# You may wish to add the `resourceNames` field to the role to further restrict
# this access in sensitive environments.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.extraLabels.role }}
  labels:
  {{- toYaml .Values.extraLabels.role | nindent 4 }}
{{- end }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]